### PR TITLE
Remove dependency on HList (via morphed) to fix compilation

### PR DESCRIPTION
**Pull request by langston-barrett**
This fixes compilation with GHC 8.4.3. HList is an old package that is no longer actively maintained, and so should not be depended on. Luckily, the part of this package that did so is not huge.

### CODE REVIEW

**Comment by langston-barrett** [comment]
@pavelchristof The second commit adds a configuration file for [Travis CI](https://travis-ci.org), which you'll have to enable for it to take effect.

The build log is here: https://travis-ci.org/siddharthist/semi-iso

**Comment by langston-barrett** [comment]
Ping @pavelchristof

**Comment by pavelchristof** [comment]
Thank you! I've enabled Travis now.

Wow, it has been a while since I wrote this library. To be honest the operators look a bit mysterious now.. :)

**Comment by langston-barrett** [comment]
@pavelchristof I would apprecate a new Hackage release if you've got the time!

**Pull request merged**
